/**************************************
 * Module: ULTRASONIC
 * File name: ultrasonic.c
 * Description: source file for the AVR ULTRASONIC driver
 * Author: amr mohsen
 *************************************/

#include "ultrasonic.h"
#include "icu.h"
#include "gpio.h"
#include"common_macros.h"
#include <util/delay.h>

 uint8 g_edgecount=0;
 uint16 g_highTime=0;




/*******************************************************************************
 *                              Functions Definitions                           *
 *******************************************************************************/
/*
 * Description :
 *  Initialize the ICU driver as required.
 *  Setup the ICU call back function.
 *  Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void)
{
	ICU_ConfigType ICU_Configurations={F_CPU_8,RAISING};
	ICU_init(&ICU_Configurations);

	ICU_setCallBack(Ultrasonic_edgeProcessing);

	GPIO_setupPinDirection(Trigger_PORT_ID,Trigger_PIN_ID,PIN_OUTPUT);  /* trigger pin */
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_LOW);                          /* INITIAL VALUE AT BEGINING */

}


/*
 * Description :
 * Send the Trigger pulse to the ultrasonic
 */
void Ultrasonic_trigger(void)
{
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_HIGH);
	_delay_us(10);
	GPIO_writePin(PORTB_ID,PIN5_ID,LOGIC_LOW);
}


/*
 * Description:
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void)
{
	uint16 distance= 0;

	Ultrasonic_trigger();

	while(g_edgecount != 2);

	g_edgecount=0;

	/* distance = ( 340 * 100cm) * time /2  = 17000 * time
	 * timer frequency = F_CPU / 8
	 * timer click = 1 / timer frequency = 1us
	 * time = g_hightime * 10^-6  (sec)
	 * therefore
	 * distance = 17000 * g_hightime * 10^-6
	 *          = 0.017 * g_hightime
	 *          = g_hightime /58.8   (cm)
	 */

	distance= (g_highTime/58 ) +1 ;             /* +1 due to fraction floating */

	return distance;

}


/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void)
{

	g_edgecount++;
	if(g_edgecount==1)
	{
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(FALLING);
	}

	else if(g_edgecount==2)
	{
		g_highTime=ICU_getInputCapturedValue();

		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(RAISING);

	}

}

