/**************************************
 * Module: ULTRASONIC
 * File name: ultrasonic.h
 * Description: header file for the AVR ULTRASONIC  driver
 * Author: amr mohsen
 *************************************/

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

#include"std_types.h"
#include"icu.h"


 /* ULTRASONIC sensor trigger PORT AND PIN Ids */
#define  Trigger_PORT_ID     PORTB_ID
#define  Trigger_PIN_ID      PIN5_ID




/*******************************************************************************
 *                              Functions Prototypes                           *
 *******************************************************************************/
/*
 * Description :
 *  Initialize the ICU driver as required.
 *  Setup the ICU call back function.
 *  Setup the direction for the trigger pin as output pin through the GPIO driver.
 */
void Ultrasonic_init(void);


/*
 * Description :
 * Send the Trigger pulse to the ultrasonic
 */
void Ultrasonic_trigger(void);


/*
 * Description:
 * Send the trigger pulse by using Ultrasonic_Trigger function.
 * Start the measurements by the ICU from this moment.
 */
uint16 Ultrasonic_readDistance(void);

/*
 * Description :
 * This is the call back function called by the ICU driver.
 * This is used to calculate the high time (pulse time) generated by the ultrasonic sensor
 */
void Ultrasonic_edgeProcessing(void);






#endif /* ULTRASONIC_H_ */
